### ISSUE TITLE
All other types of errors are ignored

### ISSUE THREAD

**Issue by C-Pro** [maddevsio/punisher#8]
If `LastStandupFor(intern.Username)` returns db error other than `sql.ErrNoRow`, it will be silently ignored. And intern will be punished I think, because of zero value in `Created` field.
https://github.com/maddevsio/punisher/blob/9f5162857dc577d77e46f8bb6a1f081eb212394c/bot/bot.go#L115

**Comment by anatoliyfedorenko** [comment]
@C-Pro will address this issue soon! Thank you for reporting!

**Comment by anatoliyfedorenko** [comment]
Resolved in https://github.com/maddevsio/punisher/commit/03a28cf9798d9b67f9ec227d881206c3fb6998a3
